---
title: "Data Example"
author: "Mark Dunning"
date: "2 February 2016"
output: html_document
---


```{r}
library(wakefield)
library(stringr)
library(dplyr)
set.seed(666)

random_patients <- function(n) {
  as.data.frame(r_data_frame(
    n,
    id,
    name,
    race,
#    age,
    sex,
    smokes,
    height_cm(name = "Height"),
    normal(name="Weight"),
    birth(random = TRUE, x = NULL, start = Sys.Date() - 365 * 45, k = 365*2,by = "1 days"),
    state,
    pet,
    grade_level(x=1:3),
    died,    
    normal_round(name="Count",digits=2),
    date_stamp)
  )
  
  
  
}

patients <- random_patients(100)
patients$Height <- round(ifelse(patients$Sex == "Male",rnorm(n=100,mean=175.3,sd=6),rnorm(n=100,161.9,sd=3)),2)
patients$Weight <- round(ifelse(patients$Sex == "Male",rnorm(n=100,mean=84,sd=6),rnorm(n=100,69,sd=3)),2)
patients$Weight <- paste0(patients$Weight, "kg")
```

1. Change some values of `Smokes` to yes/no

```{r}

rand_rows <- sample(1:100,10)
patients$Smokes[rand_rows] <- sample(c("Yes","No"),10,replace=TRUE)
```

2. Add cm to the Height column


```{r}
patients$Height <- as.character(patients$Height)
patients$Height <- paste0(patients$Height,"cm")
```


3. Add whitespace to Male / Female columns

```{r}
rand_rows <- sample(1:100,10)
patients$Sex <- as.character(patients$Sex)
patients$Sex[rand_rows] <- paste0(" ", patients$Sex[rand_rows])
rand_rows <- sample(1:100,6)
patients$Sex[rand_rows] <- paste0(patients$Sex[rand_rows], " ")

```

4. upper-case convert some of the pets

```{r}
rand_rows <- sample(1:100,10)
patients$Pet <- as.character(patients$Pet)
patients$Pet[rand_rows] <- toupper(patients$Pet[rand_rows])
```

5. convert some of the `None` pets to NA or NULL

```{r}
patients$Race <- as.character(patients$Race)
error_row <- sample(which(patients$Pet != "None"),1)
patients$Race[error_row] <- patients$Pet[error_row]

no_pet <- which(patients$Pet == "None")
patients$Pet[sample(no_pet,2)] <- "NA"
patients$Pet[sample(no_pet,3)] <- "NULL"
  
```


6. Make some of the grades '99'

```{r}
rand_rows <- sample(1:100,7)
patients$Grade_Level <- as.numeric(patients$Grade_Level)
patients$Grade_Level[rand_rows] <- 99
```

7. Put in the IDs from the diabetes data

```{r}
diabetes <- read.delim("diabetes.txt")
patients$ID <- unique(diabetes$ID)
##First 57 IDs are from centre AH


```



```{r}
head(patients)
write.table(patients, file="patient-data.txt",sep="\t",row.names = FALSE)
```


Clean the data

```{r}
library(lubridate)
grds <- patients$Grade_Level

dob <- ymd(patients$Birth)
today <- ymd("20160509")
age <- interval(dob, today)

read.delim("patient-data.txt") %>% 
  tbl_df %>% 
  mutate(Age = year(as.period(age))) %>% 
  mutate(Sex = factor(str_trim(Sex))) %>% 
  mutate(Height= as.numeric(str_replace_all(Height,pattern = "cm",""))) %>% 
  mutate(Weight = as.numeric(str_replace_all(Weight,"kg",""))) %>% 
  mutate(BMI = round((Weight/(Height/100)^2),2), Overweight = BMI > 25) %>% 
  mutate(Smokes = str_replace_all(Smokes, "Yes", TRUE)) %>% 
  mutate(Smokes = as.logical(str_replace_all(Smokes, "No", FALSE))) %>% 
  mutate(Pet = str_to_title(Pet)) %>% 
  mutate(Grade_Level = ifelse(Grade_Level == 99, NA,Grade_Level)) %>% 
  rename(Grade = Grade_Level) %>% 
  mutate(Pet = str_replace_all(Pet, "Null","NA")) %>% 
  mutate(Race = ifelse(Race %in% c("Asian","Bi-Racial","Black","Hispanic","White"), Race, NA)) -> patients_clean
 patients_clean
```


```{r}
write.table(patients_clean,file="patient-data-cleaned.txt",sep="\t",row.names = FALSE)
```

Now for a larger set

```{r}

random_patients <- function(n) {
  as.data.frame(r_data_frame(
    n,
    id,
#    name,
    race,
#    age,
    sex,
    smokes,
    height_cm(name = "Height"),
    normal(name="Weight"),
    birth(random = TRUE, x = NULL, start = Sys.Date() - 365 * 45, k = 365*2,by = "1 days"),
    state,
    pet,
    grade_level(x=1:3),
    died,    
    normal_round(name="Count",digits=2),
    date_stamp)
  )
  
  
  
}

cohort <- random_patients(10023)
cohort$Height <- round(ifelse(cohort$Sex == "Male",rnorm(n=100,mean=175.3,sd=6),rnorm(n=100,161.9,sd=3)),2)
cohort$Weight <- round(ifelse(cohort$Sex == "Male",rnorm(n=100,mean=84,sd=6),rnorm(n=100,69,sd=3)),2)
cohort$Weight <- paste0(cohort$Weight, "kg")
cohort$Height <- as.character(cohort$Height)
cohort$Height <- paste0(cohort$Height,"cm")
rand_rows <- sample(1:1000,10)
cohort$Sex <- as.character(cohort$Sex)
cohort$Sex[rand_rows] <- paste0(" ", cohort$Sex[rand_rows])
rand_rows <- sample(1:1000,6)
cohort$Sex[rand_rows] <- paste0(cohort$Sex[rand_rows], " ")
rand_rows <- sample(1:100,10)
cohort$Pet <- as.character(cohort$Pet)
cohort$Pet[rand_rows] <- toupper(cohort$Pet[rand_rows])
no_pet <- which(patients$Pet == "None")
cohort$Pet[sample(no_pet,2)] <- "NA"
cohort$Pet[sample(no_pet,3)] <- "NULL"
  
rand_rows <- sample(1:100,7)
cohort$Grade_Level <- as.numeric(cohort$Grade_Level)
cohort$Grade_Level[rand_rows] <- 99

write.table(cohort, file="cohort-data.txt",sep="\t",row.names = FALSE)

```

